mysite/eshop/urls.py
from django.urls import path

from . import views

app_name = 'eshop'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<slug>/', views.ProductDetailView.as_view(), name='product'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categories/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('subcategory/<int:pk>', views.SubCategoryDetailView.as_view(), name='subcategory-detail'),
    path('search/', views.search, name='search'),
    path('search/<slug>/', views.ProductDetailView.as_view(), name='search-product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('full-remove-from-cart/<slug>/', views.full_remove_from_cart, name='full-remove-from-cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('process-payment/', views.process_payment, name='process-payment'),
    path('payment-done/', views.payment_done, name='payment-done'),
    path('payment-cancelled/', views.payment_canceled, name='payment-cancelled'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('eshop/', include('eshop.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='eshop/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mysite/eshop/models.py
from django.db import models
from django.urls import reverse

import uuid

from django.contrib.auth.models import User

from django.db.models import Avg

from PIL import Image

from django_countries.fields import CountryField

class Product(models.Model):
    name = models.CharField('Name', max_length=200)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    sub_category = models.ForeignKey('SubCategory', on_delete=models.SET_NULL, null=True)
    description = models.TextField(
        'Description', max_length=1000, help_text='Short description of the product')
    price = models.FloatField('Price', help_text='Price of the product')
    discount_price = models.FloatField(blank=True, null=True)
    picture = models.ImageField('Picture', upload_to='pictures', null=True)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.name} {self.price}€"

    def get_absolute_url(self):
        return reverse('eshop:product', kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse('eshop:add-to-cart', kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse('eshop:remove-from-cart', kwargs={
            'slug': self.slug
        })

    @property
    def avg_rating(self):
        rating = ProductReview.objects.filter(product=self.pk).aggregate(Avg('rating'))['rating__avg']
        if rating == None:
            return None
        rounded_rating = round(rating)
        return rounded_rating

class ProductReview(models.Model):
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    Rating_CHOICES = (
        (1, 'Poor'),
        (2, 'Average'),
        (3, 'Good'),
        (4, 'Very Good'),
        (5, 'Excellent')
    )

    rating = models.IntegerField(choices=Rating_CHOICES, default=1)
    content = models.TextField('Review', max_length=2000)

class Category(models.Model):
    name = models.CharField('Name', max_length=200)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class SubCategory(models.Model):
    name = models.CharField('Name', max_length=200)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Sub category'
        verbose_name_plural = 'Sub categories'

class OrderProduct(models.Model):
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    def get_total_product_price(self):
        return self.quantity * self.product.price

    def get_total_discount_product_price(self):
        return self.quantity * self.product.discount_price

    def get_total_savings(self):
        return round(self.get_total_product_price() - self.get_total_discount_product_price(), 2)

    def get_final_price(self):
        if self.product.discount_price:
            return self.get_total_discount_product_price()
        else:
            return self.get_total_product_price()

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)

    STATUS = (
        ('order placed', 'Order placed'),
        ('in progress', 'In progress'),
        ('done', 'Done'),
        ('canceled', 'Canceled'),
    )
    status = models.CharField(
        max_length=12,
        choices=STATUS,
        blank=True,
        default='order placed',
        help_text='Status',
    )

    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.user} {self.date_created}"

    def total_cost(self):
        return sum([product.get_final_price() for product in self.orderproduct_set.all()])

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.picture.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.picture.path)

class BillingAddress(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=10)
    city = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Billing address'
        verbose_name_plural = 'Billing addresses'

mysite/eshop/views.py
from django.http import HttpResponse

from django.shortcuts import render, get_object_or_404, reverse, redirect
from .models import Product, Category, SubCategory, OrderProduct, Order, ProductReview, BillingAddress
from django.views import generic

from django.core.paginator import Paginator

from django.db.models import Q, Avg

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin

from django.template.defaulttags import register
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect

from .forms import ProductReviewForm, UserUpdateForm, ProfileUpdateForm, CheckoutForm
from django.views.generic.edit import FormMixin

from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt


def index(request):
    num_products = Product.objects.all().count()
    num_categories = Category.objects.all().count()
    num_sub_categories = SubCategory.objects.all().count()

    num_orders = Order.objects.count()

    context = {
        'num_products': num_products,
        'num_categories': num_categories,
        'num_sub_categories': num_sub_categories,
        'num_orders': num_orders,
    }

    return render(request, 'index.html', context=context)


def products(request):
    paginator = Paginator(Product.objects.all(), 6)
    page_number = request.GET.get('page')
    paged_products = paginator.get_page(page_number)
    context = {
        'products': paged_products
    }
    return render(request, 'products.html', context=context)

class OrderSummaryView(LoginRequiredMixin, generic.View):
    def get(self, *args, **kwargs):
        try:
            order = OrderProduct.objects.filter(order__user=self.request.user, ordered=False, order__ordered=False)
            total = 0
            billing_address = BillingAddress.objects.filter(user=self.request.user)
            for order_item in order:
                total += order_item.get_final_price()
            context = {
                'billing_address': billing_address,
                'object': order,
                'total': round(total, 2)  #allows only 2 decimal after dot
            }
            return render(self.request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")

class CheckoutView(LoginRequiredMixin, generic.View):
    def get(self, request, *args, **kwargs):
        form = CheckoutForm()
        context = {
            'form': form
        }
        return render(self.request, "checkout.html", context)

    def post(self, request, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                city = form.cleaned_data.get('city')
                zip = form.cleaned_data.get('zip')
                billing_address = BillingAddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    zip=zip,
                    city=city
                )
                try:
                    billing_address.save()
                except:
                    messages.warning(self.request, "Order already placed")
                    return redirect('eshop:checkout')
                order.billing_address = billing_address
                order.save()
                return redirect('eshop:process-payment')
            messages.warning(self.request, "Failed checkout")
            return redirect('eshop:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect("eshop:order-summary")

class PaymentView(generic.View):
    def get(self, request, *args, **kwargs):
        return render(self.request, "payment.html")

class ProductDetailView(FormMixin, generic.DetailView):
    model = Product
    template_name = 'product.html'
    form_class = ProductReviewForm

    def get(self, request, *args, **kwargs):
        product = self.get_object()
        if request.user.is_authenticated:
            user_review = ProductReview.objects.filter(reviewer=request.user, product=product)
            context = {
                 'product': product,
                 'user_review': user_review,
                 'form': ProductReviewForm
              }
        else:
            context = {
                'product': product,
                'form': ProductReviewForm
            }
        return render(self.request, 'product.html', context)

    def get_success_url(self):
        return reverse('eshop:product', kwargs={'slug': self.object.slug})

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['form'] = ProductReviewForm(initial={'product': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.product = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(ProductDetailView, self).form_valid(form)

@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

class CategoryListView(generic.ListView):
    model = Category
    paginate_by = 6
    template_name = 'category_list.html'

    def get(self, request, *args, **kwargs):
        lowest_prices = {}
        category_list = Category.objects.all()
        for category in category_list:
            products = Product.objects.filter(category__name=category.name)
            low_prices = 0
            for product in products:  # solution for category lowest price
                if product.discount_price:
                    if low_prices == 0:
                        low_prices = product.discount_price
                    elif low_prices > product.discount_price:
                        low_prices = product.discount_price
                else:
                    if low_prices == 0:
                        low_prices = product.price
                    elif low_prices > product.price:
                        low_prices = product.price
            lowest_prices[category.name] = low_prices
        context = {
            'lowest_prices': lowest_prices,
            'category_list': category_list,
            'get_item': get_item
        }
        return render(self.request, 'category_list.html', context)

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'category_detail.html'

    def get(self, request, *args, **kwargs):
        category = self.get_object()
        category_products = Product.objects.filter(category__name=category.name)
        context = {
            'object': category,
            'products': category_products
        }
        return render(self.request, 'category_detail.html', context)

    def get_success_url(self):
        return reverse('category-detail', kwargs={'pk': self.object.id})

class SubCategoryDetailView(generic.DetailView):
    model = SubCategory
    template_name = 'subcategory_detail.html'

    def get(self, request, *args, **kwargs):
        subcategory = self.get_object()
        subcategory_products = Product.objects.filter(sub_category__name=subcategory.name)
        context = {
            'object': subcategory,
            'products': subcategory_products
        }
        return render(self.request, 'subcategory_detail.html', context)

def search(request):
    query = request.GET.get('query')
    search_results = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'search.html', {'products': search_results, 'query': query})

@login_required
def process_payment(request):
    user_order = Order.objects.get(user=request.user, ordered=False)
    billing_address = BillingAddress.objects.get(user=request.user)
    order = get_object_or_404(Order, id=user_order.id)
    order_products = OrderProduct.objects.filter(order__user=request.user, ordered=False, order__ordered=False)
    host = request.get_host()

    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': '%.2f' % order.total_cost(),
        'invoice': 'This is invoice 79',
        'custom': str(order.id),
        'item_name': "Order {}".format(order.id),
        'address_override': 1,
        'currency_code': 'EUR',
        'address1': str(billing_address.street_address),
        'address2': str(billing_address.apartment_address),
        'country': str(billing_address.country),
        'zip': billing_address.zip,
        'city': str(billing_address.city),
        'notify_url': 'http://{}{}'.format(host,
                                           reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,
                                           reverse('eshop:payment-done')),
        'cancel_return': 'http://{}{}'.format(host,
                                              reverse('eshop:payment-cancelled')),
    }

    for product in order_products:
        product.ordered = True
        product.save()
    order.ordered = True
    order.status = "in progress"
    order.save()

mysite/eshop/templates/category_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container justify-content-center">
  <h1>{{ object.name }}</h1>

  {% if object.subcategory_set.all %}
    {% for subcat in object.subcategory_set.all %}
      <hr>
      <p>{{ subcat.name }}</p>
    {% endfor %}
  {% else %}
    <p>There are no sub-categories for this category</p>
  {% endif %}

<div class="container d-flex justify-content-center mt-50 mb-50">
    <div class="row">
        <div class="col-md-10">
            {% for p in products %}
            <div class="card card-body">
                <div class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">
                    {% if p.picture %}
                        <div class="mr-2 mb-3 mb-lg-0"> <img src="{{ p.picture.url }}" width="150" height="150" alt=""> </div>
                    {% else %}
                        <div class="card-img-actions"> <img src="{% static 'img/no-image.png' %}" class="card-img img-fluid" height="350" alt=""></div>
                    {% endif %}
                    <div class="media-body">
                        <h6 class="media-title font-weight-semibold"> <a href="{{ p.get_absolute_url }}" data-abc="true">{{ p.name }}</a> </h6>
                        <ul class="list-inline list-inline-dotted mb-3 mb-lg-2">
                            <li class="list-inline-item"><a href="#" class="text-muted" data-abc="true">{{ p.category }} - {{ p.sub_category }}</a></li>
                        </ul>
                        <p class="mb-3">{{ p.description|truncatechars:255 }}</p>
                    </div>
                    <div class="mt-3 mt-lg-0 ml-lg-3 text-center">
                        <h3 class="mb-0 font-weight-semibold">€
                                {% if p.discount_price %}
                                {{ p.discount_price }}
                                {% else %}
                                {{ p.price }}
                                {% endif %}</h3>
                        <div> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
                        <div class="text-muted">number of reviews</div>
                        {% if user.is_authenticated %}
                            <a href="{{ p.get_add_to_cart_url }}" class="btn bg-cart">Add to cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>
{% endblock %}

mysite/eshop/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid justify-content-center">
<table class="table pr-0">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total Product Price</th>
    </tr>
  </thead>
  <tbody>
    {% for order_item in object %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ order_item.product.name }}</td>
      <td>{% if order_item.product.discount_price %}
          {{ order_item.product.discount_price }}
          {% else %}
          {{ order_item.product.price }}
          {% endif %}
      </td>
      <td>
          <a href="{% url 'eshop:remove-from-cart' order_item.product.slug %}" ><i class="fas fa-minus mr-2"></i></a>
          {{ order_item.quantity }}
          <a href="{% url 'eshop:add-to-cart' order_item.product.slug %}"><i class="fas fa-plus ml-2"></i></a></td>
      <td>
          {% if order_item.product.discount_price %}
          {{ order_item.get_total_discount_product_price }}
          <span class="badge badge-info">Saving: €{{ order_item.get_total_savings }}</span>
          {% else %}
          {{ order_item.get_total_product_price }}
          {% endif %}
          <a href="{% url 'eshop:full-remove-from-cart' order_item.product.slug %}"><i class="fas fa-times float-right"></i></a>
      </td>
    </tr>
    {% endfor %}
    {% if total < 0.01 %}
    <tr>
        <td colspan="6">Your cart is empty</td>
    </tr>
    <tr>
        <td colspan="6">
            <a class="btn btn-primary float-right" href="/">Continue shopping</a>
        </td>
    </tr>
    {% else %}
    <tr>
        <td colspan="4"><strong>Order Total</strong></td>
        <td><strong>€{{ total }}</strong></td>
    </tr>
    <tr>
        <td colspan="6">
            {% if not billing_address %}
                <a class="btn btn-warning float-right ml-2" href="{% url 'eshop:checkout' %}">Proceed to checkout</a>
            {% else %}
                <a class="btn btn-warning float-right ml-2" href="{% url 'eshop:process-payment' %}">Proceed to checkout</a>
            {% endif %}
            <a class="btn btn-primary float-right" href="/">Continue shopping</a>
        </td>
    </tr>
    {% endif %}
  </tbody>
</table>
</div>

{% endblock %}

mysite/eshop/templates/payment_cancelled.html
{% extends 'base.html' %}

{% block content %}

    <p>Payment cancelled. :(</p>

{% endblock %}

mysite/eshop/templates/payment_done.html
{% extends 'base.html' %}

{% block content %}

    <p>Payment done. :)</p>

{% endblock %}

mysite/eshop/templates/product.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
        {% endfor %}
    {% endif %}
    <div class="container product">
        <h3>{{ product.name }}</h3>
        <h4 class="text-muted">{{ product.category }} - {{ product.sub_category }}</h4>
        <img src="{{ product.picture.url }}" class="card-img img-fluid" height="350" alt="">
        <hr/>
        <p>{{ product.description }}</p>
        </hr>
        </br>
        <h5>
            {% if product.discount_price %}
                <span class="mr-1">
                        <del>€{{ product.price }}</del>
                    </span>
                <span><strong>€{{ product.discount_price }}</strong></span>
            {% else %}
                <span>€{{ product.price }}</span>
            {% endif %}
        </h5>
        {% if user.is_authenticated %}
            <a href="{{ product.get_add_to_cart_url }}" class="btn bg-cart">Add to cart</a>
        {% endif %}
    </div>
    </br>
    {% if product.avg_rating %}
        {% if product.avg_rating == 1 %}
        <i class="fa fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i
                class="far fa-star"></i>
        {% elif product.avg_rating == 2 %}
        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i
                class="far fa-star"></i>
        {% elif product.avg_rating == 3 %}
        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="far fa-star"></i><i
                class="far fa-star"></i>
        {% elif product.avg_rating == 4 %}
        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                class="far fa-star"></i>
        {% elif product.avg_rating == 5 %}
        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                class="fa fa-star"></i>
        {% endif %}
    ({{ product.productreview_set.all|length }})
    {% else %}
        <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i
                class="far fa-star"></i>
        <p>No ratings</p>
    {% endif %}
    {% if user.is_authenticated %}
        {% if user_review %}
        {% else %}
            <div class="fieldWrapper">
                <hr>
                <br/>
                <h4>Leave a comment:</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.content }}
                    {{ form.rating }}
                    <input type="submit" value="Submit">
                </form>
            </div>
        {% endif %}
    {% endif %}
    <h4>Reviews:</h4>
    {% if product.productreview_set.all %}
        {% for review in product.productreview_set.all %}
            <hr>
            <img class="profile-picture rounded-circle" src="{{ review.reviewer.profile.picture.url }}" />
            <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
            <div>
                {% if review.rating == 1 %}
                <i class="fa fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i
                    class="far fa-star"></i>
                {% elif review.rating == 2 %}
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i
                    class="far fa-star"></i>
                {% elif review.rating == 3 %}
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="far fa-star"></i><i
                    class="far fa-star"></i>
                {% elif review.rating == 4 %}
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                    class="far fa-star"></i>
                {% else %}
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                    class="fa fa-star"></i>
                {% endif %}
            </div>
            <p>{{ review.content }}</p>
        {% endfor %}
    {% else %}
        <p>This product doesn't have any reviews yet</p>
    {% endif %}

{% endblock %}

mysite/eshop/templates/subcategory_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container justify-content-center">
  <h1>{{ object.name }}</h1>

<div class="container d-flex justify-content-center mt-50 mb-50">
    <div class="row">
        <div class="col-md-10">
          {% if products %}
            {% for p in products %}
            <div class="card card-body">
                <div class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">
                    {% if p.picture %}
                        <div class="mr-2 mb-3 mb-lg-0"> <img src="{{ p.picture.url }}" width="150" height="150" alt=""> </div>
                    {% else %}
                        <div class="card-img-actions"> <img src="{% static 'img/no-image.png' %}" class="card-img img-fluid" height="350" alt=""></div>
                    {% endif %}
                    <div class="media-body">
                        <h6 class="media-title font-weight-semibold"> <a href="{{ p.get_absolute_url }}" data-abc="true">{{ p.name }}</a> </h6>
                        <ul class="list-inline list-inline-dotted mb-3 mb-lg-2">
                            <li class="list-inline-item"><a href="#" class="text-muted" data-abc="true">{{ p.category }} - {{ p.sub_category }}</a></li>
                        </ul>
                        <p class="">{{ p.description|truncatechars:255 }}</p>
                    </div>
                    <div class="mt-3 mt-lg-0 ml-lg-3 text-center">
                        <h3 class="mb-0 font-weight-semibold">€
                                {% if p.discount_price %}
                                {{ p.discount_price }}
                                <span class="badge badge-danger">SALE</span>
                                {% else %}
                                {{ p.price }}
                                {% endif %}</h3>
                        <div>
                                {% if p.avg_rating %}
                                    {% if p.avg_rating == 1 %}
                                        <i class="fa fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                                    {% elif p.avg_rating == 2 %}
                                        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                                    {% elif p.avg_rating == 3 %}
                                        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                                    {% elif p.avg_rating == 4 %}
                                        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="far fa-star"></i>
                                    {% elif p.avg_rating == 5 %}
                                        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
                                    {% endif %}
                                ({{ p.productreview_set.all|length }})
                                {% else %}
                                    <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                                    ({{ p.productreview_set.all|length }})
                                {% endif %}
                        </div>
                        {% if user.is_authenticated %}
                            <a href="{{ p.get_add_to_cart_url }}" class="btn bg-cart">Add to cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
          {% else %}
            <div class="container-fluid w-100">
              <h1>There are no products in this category</h1>
            </div>
          {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}